services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: passwd
    volumes:
      - ./sql:/var/lib/postgresql/data/sql
    ports:
      - 5433:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

  cache:
    image: redis/redis-stack-server:latest
    restart: always
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "BF.EXISTS", "bf_seckill_events", "1"]
      interval: 5s
      timeout: 3s
      retries: 10
